/*
Visier Object Configuration APIs

Visier APIs for managing objects in studio experience

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  ObjectConfigurationApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { VisierObjectConfigurationCustom } from "./client-custom";

export class VisierObjectConfiguration extends VisierObjectConfigurationCustom {
  readonly objectConfiguration: ObjectConfigurationApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.objectConfiguration = new ObjectConfigurationApi(configuration);
  }

}
