/*
Visier Object Configuration APIs

Visier APIs for managing objects in studio experience

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DimensionFilterDTO } from './dimension-filter-dto';

/**
 * 
 * @export
 * @interface AnalyticObjectFilterDTO
 */
export interface AnalyticObjectFilterDTO {
    /**
     * The UUID of the analytic object used in the selection concept.
     * @type {string}
     * @memberof AnalyticObjectFilterDTO
     */
    'analyticObjectUuid'?: string;
    /**
     * The symbol name of the analytic object.
     * @type {string}
     * @memberof AnalyticObjectFilterDTO
     */
    'symbolName'?: string;
    /**
     * A list of dimensions included in the concept.
     * @type {Array<DimensionFilterDTO>}
     * @memberof AnalyticObjectFilterDTO
     */
    'dimensions'?: Array<DimensionFilterDTO>;
}

