/*
Visier Object Configuration APIs

Visier APIs for managing objects in studio experience

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CalculationConceptConfigurationDTO } from './calculation-concept-configuration-dto';

/**
 * 
 * @export
 * @interface CalculationConceptDTO
 */
export interface CalculationConceptDTO {
    /**
     * The unique identifier associated with the calculation concept.
     * @type {string}
     * @memberof CalculationConceptDTO
     */
    'uuid'?: string;
    /**
     * The display name of the calculation concept.
     * @type {string}
     * @memberof CalculationConceptDTO
     */
    'name'?: string;
    /**
     * A list of objects representing the configuration for the calculation concept.
     * @type {CalculationConceptConfigurationDTO}
     * @memberof CalculationConceptDTO
     */
    'configuration'?: CalculationConceptConfigurationDTO;
}

