/*
Visier Object Configuration APIs

Visier APIs for managing objects in studio experience

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CalculationConceptDTO } from './calculation-concept-dto';

/**
 * 
 * @export
 * @interface CalculationConceptListDTO
 */
export interface CalculationConceptListDTO {
    /**
     * A list of objects representing calculation concepts.
     * @type {Array<CalculationConceptDTO>}
     * @memberof CalculationConceptListDTO
     */
    'concepts'?: Array<CalculationConceptDTO>;
}

