/*
Visier Object Configuration APIs

Visier APIs for managing objects in studio experience

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PerspectiveConfigurationDTO } from './perspective-configuration-dto';

/**
 * 
 * @export
 * @interface CalculationConceptConfigurationDTO
 */
export interface CalculationConceptConfigurationDTO {
    /**
     * A list of objects representing the perspectives in the calculation concept.
     * @type {Array<PerspectiveConfigurationDTO>}
     * @memberof CalculationConceptConfigurationDTO
     */
    'perspectives'?: Array<PerspectiveConfigurationDTO>;
}

