/*
Visier Object Configuration APIs

Visier APIs for managing objects in studio experience

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PerspectiveConfigurationDTO } from './perspective-configuration-dto';

/**
 * The configuration to apply to the concept.
 * @export
 * @interface CalculationConceptConfigurationMapDTO
 */
export interface CalculationConceptConfigurationMapDTO {
    /**
     * A list of objects representing the list of perspectives in the calculation concept.
     * @type {Array<PerspectiveConfigurationDTO>}
     * @memberof CalculationConceptConfigurationMapDTO
     */
    'perspectivesToMap'?: Array<PerspectiveConfigurationDTO>;
}

