/*
Visier Object Configuration APIs

Visier APIs for managing objects in studio experience

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DimensionMemberDTO } from './dimension-member-dto';

/**
 * 
 * @export
 * @interface DimensionFilterDTO
 */
export interface DimensionFilterDTO {
    /**
     * The UUID of the dimension.
     * @type {string}
     * @memberof DimensionFilterDTO
     */
    'dimensionId'?: string;
    /**
     * The symbol name of the dimension.
     * @type {string}
     * @memberof DimensionFilterDTO
     */
    'symbolName'?: string;
    /**
     * A list of dimension members to map to the perspective node.   Note: If this array is empty, all dimension members will be removed for the node.
     * @type {Array<DimensionMemberDTO>}
     * @memberof DimensionFilterDTO
     */
    'dimensionMembers'?: Array<DimensionMemberDTO>;
}

