/*
Visier Object Configuration APIs

Visier APIs for managing objects in studio experience

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DimensionMemberDTO
 */
export interface DimensionMemberDTO {
    /**
     * A list of strings representing the dimension members. Dimension members in a hierarchical dimension  will have an array with multiple strings.
     * @type {Array<string>}
     * @memberof DimensionMemberDTO
     */
    'dimensionMember'?: Array<string>;
}

