/*
Visier Object Configuration APIs

Visier APIs for managing objects in studio experience

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AnalyticObjectFilterDTO } from './analytic-object-filter-dto';

/**
 * 
 * @export
 * @interface PerspectiveNodeDTO
 */
export interface PerspectiveNodeDTO {
    /**
     * The UUID of the node\'s selection concept. Perspective nodes are generated as selection concepts to enable filtering.
     * @type {string}
     * @memberof PerspectiveNodeDTO
     */
    'selectionConceptUuid'?: string;
    /**
     * The symbol name of the selection concept. For example, \"isExitActualSystemTermination\".
     * @type {string}
     * @memberof PerspectiveNodeDTO
     */
    'symbolName'?: string;
    /**
     * A list of analytic object filters indicating the analytic object and dimensions used for the selection concept.
     * @type {Array<AnalyticObjectFilterDTO>}
     * @memberof PerspectiveNodeDTO
     */
    'analyticObjectFilters'?: Array<AnalyticObjectFilterDTO>;
}

