/*
Visier Object Configuration APIs

Visier APIs for managing objects in studio experience

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PerspectiveNodeDTO } from './perspective-node-dto';

/**
 * 
 * @export
 * @interface PerspectiveConfigurationDTO
 */
export interface PerspectiveConfigurationDTO {
    /**
     * The UUID of the perspective.
     * @type {string}
     * @memberof PerspectiveConfigurationDTO
     */
    'perspectiveId'?: string;
    /**
     * The display name of the perspective.
     * @type {string}
     * @memberof PerspectiveConfigurationDTO
     */
    'perspectiveName'?: string;
    /**
     * A list of nodes in the perspective.
     * @type {Array<PerspectiveNodeDTO>}
     * @memberof PerspectiveConfigurationDTO
     */
    'perspectiveNodes'?: Array<PerspectiveNodeDTO>;
}

