/*
Visier Object Configuration APIs

Visier APIs for managing objects in studio experience

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SelectionConceptDTO } from './selection-concept-dto';

/**
 * 
 * @export
 * @interface SelectionConceptListDTO
 */
export interface SelectionConceptListDTO {
    /**
     * A list of objects representing selection concepts.
     * @type {Array<SelectionConceptDTO>}
     * @memberof SelectionConceptListDTO
     */
    'concepts'?: Array<SelectionConceptDTO>;
}

