/*
Visier Object Configuration APIs

Visier APIs for managing objects in studio experience

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AnalyticObjectFilterDTO } from './analytic-object-filter-dto';

/**
 * 
 * @export
 * @interface SelectionConceptConfigurationMapDTO
 */
export interface SelectionConceptConfigurationMapDTO {
    /**
     * A list of analytic object filters indicating the analytic object and dimension members used  for the selection concept.   Note: If this array is empty, all filters will be removed for the concept.
     * @type {Array<AnalyticObjectFilterDTO>}
     * @memberof SelectionConceptConfigurationMapDTO
     */
    'analyticObjectFiltersToMap'?: Array<AnalyticObjectFilterDTO>;
}

