/*
Visier Object Configuration APIs

Visier APIs for managing objects in studio experience

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AnalyticObjectFilterDTO } from './analytic-object-filter-dto';

/**
 * 
 * @export
 * @interface SelectionConceptConfigurationDTO
 */
export interface SelectionConceptConfigurationDTO {
    /**
     * A list of analytic object filters indicating the analytic object and dimension used for this selection concept.
     * @type {Array<AnalyticObjectFilterDTO>}
     * @memberof SelectionConceptConfigurationDTO
     */
    'analyticObjectFilters'?: Array<AnalyticObjectFilterDTO>;
}

